resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: npm

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - /src/front

steps:
- task: NodeTool@0
  displayName: 'Use Node 8.11.0'
  inputs:
    versionSpec: 8.11.0


- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: src/front

    verbose: false


- task: Npm@1
  displayName: 'npm install @angular/cli'
  inputs:
    command: custom

    workingDir: src/front

    verbose: false

    customCommand: 'install @angular/cli@7.0.4'


- task: Npm@1
  displayName: linter
  inputs:
    command: custom

    workingDir: src/front

    verbose: false

    customCommand: 'run lint'


- task: Npm@1
  displayName: 'npm run test'
  inputs:
    command: custom

    workingDir: src/front

    verbose: false

    customCommand: 'run test-headless'


- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '**/testsResults.xml'


- task: Npm@1
  displayName: 'production build'
  inputs:
    command: custom

    workingDir: src/front

    verbose: false

    customCommand: 'run build:prod'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: src/front/dist
